Mush\Daedalus\Entity\ClosedDaedalus:
  attributes:                          # optional
    id:
      groups: [ 'closed_daedalus_read' ]
    endCause:
      groups: [ 'closed_daedalus_read' ]
    endDay:
      groups: [ 'closed_daedalus_read' ]
    endCycle:
      groups: [ 'closed_daedalus_read' ]
    players:
      groups: [ 'closed_daedalus_read' ]
    numberOfHuntersKilled:
      groups: [ 'closed_daedalus_read' ]
    daysSurvived:
      groups: [ 'closed_daedalus_read' ]
    cyclesSurvived:
      groups: [ 'closed_daedalus_read' ]
    language:
      groups: [ 'closed_daedalus_read' ]
