Mush\Modifier\Entity\Config\DirectModifierConfig:
  attributes:
    id:
      groups: [ 'modifier_config_read' ]
    name:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierName:
      groups: [ 'modifier_config_read' , 'modifier_config_write' ]
    modifierRange:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    reverseOnRemove:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    triggeredEvent:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierActivationRequirements:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetFilters:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
