Mush\Game\Entity\GameConfig:
  attributes:                          # optional
    id:
      groups: [ 'game_config_read' ]
    name:
      groups: [ 'game_config_read', 'game_config_write' ]
    daedalusConfig:
      groups: [ 'game_config_read', 'game_config_write' ]
    difficultyConfig:
      groups: [ 'game_config_read', 'game_config_write' ]
    charactersConfig:
      groups: [ 'game_config_write' ]
    equipmentsConfig:
      groups: [ 'game_config_write' ]
    statusConfigs:
      groups: [ 'game_config_write' ]
    triumphConfig:
      groups: [ 'game_config_write' ]
    diseaseCauseConfig:
      groups: [ 'game_config_write' ]
    diseaseConfig:
      groups: [ 'game_config_write' ]
    consumableDiseaseConfig:
      groups: [ 'game_config_write' ]
    hunterConfigs:
      groups: [ 'game_config_write' ]
    titleConfigs:
      groups: [ 'game_config_write' ]
