services:
    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager:
        public: true
    WebPush\WebPushService:
        class: Mush\Tests\unit\TestDoubles\Service\FakeWebPushService
        public: true
    Mush\User\Query\SearchUsersByUsernameQueryHandler:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'
        public: true
