daedalus:
    resource: ../../src/Daedalus/Controller/
    type: annotation
    prefix: /api/v1
player:
    resource: ../../src/Player/Controller/
    type: annotation
    prefix: /api/v1
user:
    resource: ../../src/User/Controller/
    type: annotation
    prefix: /api/v1
oauth:
    resource: ../../src/User/Controller/LoginController.php
    type: annotation
    prefix: /oauth
action:
    resource: ../../src/Action/Controller/
    type: annotation
    prefix: /api/v1
room-log:
    resource: ../../src/RoomLog/Controller/
    type: annotation
    prefix: /api/v1
communication:
    resource: ../../src/Communication/Controller/
    type: annotation
    prefix: /api/v1
#game:
#    resource: ../../src/Game/Controller/
#    type: annotation
#    prefix: /api/v1
alert:
    resource: ../../src/Alert/Controller/
    type: annotation
    prefix: /api/v1
metagame:
    resource: ../../src/MetaGame/Controller/
    type: annotation
    prefix: /api/v1
exploration:
    resource: ../../src/Exploration/Controller/
    type: annotation
    prefix: /api/v1

api_login_check:
    path: /api/login_check

kernel:
    resource: ../../src/Kernel.php
    type: annotation
